= PS@E Hello World Lab
Matt Stine <mstine@gopivotal.com>, Scott Frederick <sfrederick@gopivotal.com>

== Prerequisites

* Gradle: Install via either http://brew.sh/[Homebrew] (+brew install gradle+) or http://gvmtool.net/[GVM].

== Intro

This lab will guide you through building a basic ``Hello World'' style application. You will utilize a combination of Spring Boot, Spring Data, and Spring Cloud. You'll also leverage a large dataset to show the power of paging, sorting, and searching with Spring Data REST.

This exercise is based on https://github.com/scottfrederick/spring-boot-cities which was created by Scott Frederick.

== Steps

=== Getting Started

. Browse to http://start.spring.io[Spring Initializr] and complete the form as follows:
+
Group:: org.example
Artifact:: cities
Name:: cities
Description:: Demo project
Package name:: org.example.cities
Styles:: Actuator, JPA, Rest Repositories, Web
Type:: Maven project

+
Then click +Generate+. This will result in a file called +starter.zip+ being downloaded to your workstation.

. Create a directory to house your code, and into that directory unzip +starter.zip+.

. Optionally run your favorite of +gradle idea+ or +gradle eclipse+. Then open the project in your favorite editor or IDE of choice.

. Add a runtime dependency on the http://hsqldb.org/[HyperSQL in-memory database] to +build.gradle+:
+
[source,groovy]
----
dependencies {
    // ...
    runtime("org.hsqldb:hsqldb")
}
----

. Create the package +org.example.cities.model+ and in that package create the class +City+. Into that file you can paste the following source code, which represents cities based on postal codes, global coordinates, etc:
+
[source,java]
----
@Entity
@Table(name="city")
public class City implements Serializable {
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue
    private long id;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String county;

    @Column(nullable = false)
    private String stateCode;

    @Column(nullable = false)
    private String postalCode;

    @Column
    private String latitude;

    @Column
    private String longitude;
}
----
+
Notice that we're using JPA annotations for everything. You'll need to use your favorite IDE's features to add the appropriate import statements as well as getters and setters.

. Create the package +org.example.cities.repositories+ and in that package create the interface +CityRepository+. Paste the following code and add appropriate imports:
+
[source,java]
----
@RepositoryRestResource(collectionResourceRel = "cities", path = "cities")
public interface CityRepository extends PagingAndSortingRepository<City, Long> {
}
----

. Add JPA and REST Repository support to +Application+ class.
+
[source,java]
----
@Configuration
@ComponentScan
@EnableAutoConfiguration
@EnableJpaRepositories // <---- Add this
@Import(RepositoryRestMvcConfiguration.class) // <---- And this
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
----

. Build the application:
+
[source,bash]
----
$ gradle assemble
----

. Run the application:
+
[source,bash]
----
$ java -jar build/libs/cities-0.0.1-SNAPSHOT.jar
----

. Access the application using +curl+. You'll see that the primary endpoint automatically exposes the ability to page, size, and sort the response JSON. So what have you done? Created three classes and one build file, resulting in a fully-functional REST micro-service. The application's +DataSource+ is created automatically by Boot using the in-memory database because no other +DataSource+ was detected in the project.
+
[source,bash]
----
$ curl -i localhost:8080/cities
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: application
Content-Type: application/hal+json
Transfer-Encoding: chunked
Date: Tue, 27 May 2014 19:34:45 GMT

{
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/cities{?page,size,sort}",
      "templated" : true
    }
  },
  "page" : {
    "size" : 20,
    "totalElements" : 0,
    "totalPages" : 0,
    "number" : 0
  }
}
----
+
Next we'll import some data.

=== Importing Data

. Add https://github.com/pivotalservices/pse-training-cf-hw-module/blob/master/code/src/main/resources/import.sql to +src/main/resources+. This is a rather large data set containing all of the postal codes in the United States (and its territories). This file will automatically be picked up by Boot and run by Hibernate.

. Build the application:
+
[source,bash]
----
$ gradle assemble
----

. Run the application:
+
[source,bash]
----
$ java -jar build/libs/cities-0.0.1-SNAPSHOT.jar
----

. Access the application again using +curl+. Notice the appropriate hypermedia is included for next, previous, and self. You can also select pages and page size by utilizing +?size=n&page=n+ on the URL string. Finally, you can sort the data utilizing +?sort=fieldName+.
+
[source,bash]
----
curl -i localhost:8080/cities
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: application
Content-Type: application/hal+json
Transfer-Encoding: chunked
Date: Tue, 27 May 2014 19:59:58 GMT

{
  "_links" : {
    "next" : {
      "href" : "http://localhost:8080/cities?page=1&size=20"
    },
    "self" : {
      "href" : "http://localhost:8080/cities{?page,size,sort}",
      "templated" : true
    }
  },
  "_embedded" : {
    "cities" : [ {
      "name" : "HOLTSVILLE",
      "county" : "SUFFOLK",
      "stateCode" : "NY",
      "postalCode" : "00501",
      "latitude" : "+40.922326",
      "longitude" : "-072.637078",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/1"
        }
      }
    }, {
      "name" : "HOLTSVILLE",
      "county" : "SUFFOLK",
      "stateCode" : "NY",
      "postalCode" : "00544",
      "latitude" : "+40.922326",
      "longitude" : "-072.637078",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/2"
        }
      }
    }, {
      "name" : "ADJUNTAS",
      "county" : "ADJUNTAS",
      "stateCode" : "PR",
      "postalCode" : "00601",
      "latitude" : "+18.165273",
      "longitude" : "-066.722583",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/3"
        }
      }
    }, {
      "name" : "AGUADA",
      "county" : "AGUADA",
      "stateCode" : "PR",
      "postalCode" : "00602",
      "latitude" : "+18.393103",
      "longitude" : "-067.180953",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/4"
        }
      }
    }, {
      "name" : "AGUADILLA",
      "county" : "AGUADILLA",
      "stateCode" : "PR",
      "postalCode" : "00603",
      "latitude" : "+18.455913",
      "longitude" : "-067.145780",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/5"
        }
      }
    }, {
      "name" : "AGUADILLA",
      "county" : "AGUADILLA",
      "stateCode" : "PR",
      "postalCode" : "00604",
      "latitude" : "+18.493520",
      "longitude" : "-067.135883",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/6"
        }
      }
    }, {
      "name" : "AGUADILLA",
      "county" : "AGUADILLA",
      "stateCode" : "PR",
      "postalCode" : "00605",
      "latitude" : "+18.465162",
      "longitude" : "-067.141486",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/7"
        }
      }
    }, {
      "name" : "MARICAO",
      "county" : "MARICAO",
      "stateCode" : "PR",
      "postalCode" : "00606",
      "latitude" : "+18.172947",
      "longitude" : "-066.944111",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/8"
        }
      }
    }, {
      "name" : "ANASCO",
      "county" : "ANASCO",
      "stateCode" : "PR",
      "postalCode" : "00610",
      "latitude" : "+18.288685",
      "longitude" : "-067.139696",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/9"
        }
      }
    }, {
      "name" : "ANGELES",
      "county" : "UTUADO",
      "stateCode" : "PR",
      "postalCode" : "00611",
      "latitude" : "+18.279531",
      "longitude" : "-066.802170",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/10"
        }
      }
    }, {
      "name" : "ARECIBO",
      "county" : "ARECIBO",
      "stateCode" : "PR",
      "postalCode" : "00612",
      "latitude" : "+18.450674",
      "longitude" : "-066.698262",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/11"
        }
      }
    }, {
      "name" : "ARECIBO",
      "county" : "ARECIBO",
      "stateCode" : "PR",
      "postalCode" : "00613",
      "latitude" : "+18.458093",
      "longitude" : "-066.732732",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/12"
        }
      }
    }, {
      "name" : "ARECIBO",
      "county" : "ARECIBO",
      "stateCode" : "PR",
      "postalCode" : "00614",
      "latitude" : "+18.429675",
      "longitude" : "-066.674506",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/13"
        }
      }
    }, {
      "name" : "BAJADERO",
      "county" : "ARECIBO",
      "stateCode" : "PR",
      "postalCode" : "00616",
      "latitude" : "+18.444792",
      "longitude" : "-066.640678",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/14"
        }
      }
    }, {
      "name" : "BARCELONETA",
      "county" : "BARCELONETA",
      "stateCode" : "PR",
      "postalCode" : "00617",
      "latitude" : "+18.447092",
      "longitude" : "-066.544255",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/15"
        }
      }
    }, {
      "name" : "BOQUERON",
      "county" : "CABO ROJO",
      "stateCode" : "PR",
      "postalCode" : "00622",
      "latitude" : "+17.998531",
      "longitude" : "-067.187318",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/16"
        }
      }
    }, {
      "name" : "CABO ROJO",
      "county" : "CABO ROJO",
      "stateCode" : "PR",
      "postalCode" : "00623",
      "latitude" : "+18.062201",
      "longitude" : "-067.149541",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/17"
        }
      }
    }, {
      "name" : "PENUELAS",
      "county" : "PENUELAS",
      "stateCode" : "PR",
      "postalCode" : "00624",
      "latitude" : "+18.023535",
      "longitude" : "-066.726156",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/18"
        }
      }
    }, {
      "name" : "CAMUY",
      "county" : "CAMUY",
      "stateCode" : "PR",
      "postalCode" : "00627",
      "latitude" : "+18.477891",
      "longitude" : "-066.854770",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/19"
        }
      }
    }, {
      "name" : "CASTANER",
      "county" : "LARES",
      "stateCode" : "PR",
      "postalCode" : "00631",
      "latitude" : "+18.269187",
      "longitude" : "-066.864993",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/20"
        }
      }
    } ]
  },
  "page" : {
    "size" : 20,
    "totalElements" : 42741,
    "totalPages" : 2138,
    "number" : 0
  }
}
----

. Try the following +curl+ statements to see how the application behaves:
+
[source,bash]
----
$ curl -i "localhost:8080/cities?size=5"
$ curl -i "localhost:8080/cities?size=5&page=3"
$ curl -i "localhost:8080/cities?sort=postalCode,desc"
----
+
Next we'll add searching capabilities.
