= PS@E Hello World Lab
Matt Stine <mstine@gopivotal.com>, Scott Frederick <sfrederick@gopivotal.com>

== Prerequisites

* Gradle: Install via either http://brew.sh/[Homebrew] (+brew install gradle+) or http://gvmtool.net/[GVM].

== Intro

This lab will guide you through building a basic ``Hello World'' style application. You will utilize a combination of Spring Boot, Spring Data, and Spring Cloud. You'll also leverage a large dataset to show the power of paging, sorting, and searching with Spring Data REST.

== Steps

=== Getting Started

. Browse to http://start.spring.io[Spring Initializr] and complete the form as follows:
+
Group:: org.example
Artifact:: cities
Name:: cities
Description:: Demo project
Package name:: org.example.cities
Styles:: Actuator, JPA, Rest Repositories, Web
Type:: Maven project

+
Then click +Generate+. This will result in a file called +starter.zip+ being downloaded to your workstation.

. Create a directory to house your code, and into that directory unzip +starter.zip+.

. Optionally run your favorite of +gradle idea+ or +gradle eclipse+. Then open the project in your favorite editor or IDE of choice.

. Add a runtime dependency on the http://www.h2database.com[H2 in-memory database] to +build.gradle+:
+
[source,groovy]
----
dependencies {
    // ...
    runtime("org.hsqldb:hsqldb")
}
----

. Create the package +org.example.cities.model+ and in that package create the class +City+. Into that file you can paste the following source code, which represents cities based on postal codes, global coordinates, etc:
+
[source,java]
----
@Entity
@Table(name="city")
public class City implements Serializable {
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue
    private long id;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String county;

    @Column(nullable = false)
    private String stateCode;

    @Column(nullable = false)
    private String postalCode;

    @Column
    private String latitude;

    @Column
    private String longitude;
}
----
+
Notice that we're using JPA annotations for everything. You'll need to use your favorite IDE's features to add the appropriate import statements as well as getters and setters.

. Create the package +org.example.cities.repositories+ and in that package create the interface +CityRepository+. Paste the following code and add appropriate imports:
+
[source,java]
----
@RepositoryRestResource(collectionResourceRel = "cities", path = "cities")
public interface CityRepository extends PagingAndSortingRepository<City, Long> {
}
----

. Add JPA and REST Repository support to +Application+ class.
+
[source,java]
----
@Configuration
@ComponentScan
@EnableAutoConfiguration
@EnableJpaRepositories // <---- Add this
@Import(RepositoryRestMvcConfiguration.class) // <---- And this
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
----

. Build the application:
+
[source,bash]
----
$ gradle assemble
----

. Run the application:
+
[source,bash]
----
$ java -jar build/libs/cities-0.0.1-SNAPSHOT.jar
----

. Access the application using +curl+. You'll see that the primary endpoint automatically exposes the ability to page, size, and sort the response JSON. So what have you done? Created three classes and one build file, resulting in a fully-functional REST micro-service. The application's +DataSource+ is created automatically by Boot using the in-memory database because no other +DataSource+ was detected in the project.
+
[source,bash]
----
$ curl -i localhost:8080/cities
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: application
Content-Type: application/hal+json
Transfer-Encoding: chunked
Date: Tue, 27 May 2014 19:34:45 GMT

{
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/cities{?page,size,sort}",
      "templated" : true
    }
  },
  "page" : {
    "size" : 20,
    "totalElements" : 0,
    "totalPages" : 0,
    "number" : 0
  }
}
----
+
Next we'll import some data.

=== Importing Data
